name: Build and deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install mkdocs-material
      - name: Build and deploy
        run: |
          mkdocs build
          mkdocs gh-deploy